#!/usr/bin/env bash
#
# Release guard: prove the plugin zip about to be published reports the tag
# it was built from.
#
# Why this exists (#91). The v0.10.0 release zip's MANIFEST.MF declared
# Plugin-Version: 0.8.0 — two releases behind the v0.10.0 tag it shipped
# under. `Plugin-Version` is generated by the nextflow-plugin Gradle
# toolchain FROM build.gradle's `version` property at build time; the
# existing "tag == build.gradle version" release-workflow check (added
# alongside the very first release workflow) should have caught this, but it
# only greps the SOURCE FILE's `version = '...'` line — it never looks at
# what actually ended up inside the built zip. A stray edit to the generated
# manifest, a stale build cache, or a toolchain that stops reading that
# property would all pass the source-line check while still shipping a wrong
# manifest, exactly as happened here.
#
# This script closes that gap: it builds the plugin zip for real, unzips it,
# reads MANIFEST.MF's actual Plugin-Version, and compares that — not the
# source line — against the tag.
#
# Usage: check-release-version.sh <tag> [zip_path]
#   check-release-version.sh v0.11.0                          # builds via gradlew
#   check-release-version.sh v0.11.0 build/distributions/x.zip # checks a given zip, no build
# Run from the repo root (needs build.gradle, gradlew, settings.gradle here)
# unless a zip_path is given, in which case only that zip is inspected — this
# is what the companion Spock test uses to feed a hand-crafted manifest
# without invoking Gradle.
set -euo pipefail

tag="${1:-}"
zip_override="${2:-}"
if [ -z "$tag" ]; then
  echo "usage: $0 <tag> [zip_path]   (e.g. v0.11.0)" >&2
  exit 2
fi

# The tag is vX.Y.Z; build.gradle's `version` and the manifest's
# Plugin-Version are both the un-prefixed form.
want="${tag#v}"

fail=0
note() { echo "::error::$*" >&2; fail=1; }

if [ -n "$zip_override" ]; then
  zip_path="$zip_override"
  if [ ! -f "$zip_path" ]; then
    note "given zip '$zip_path' does not exist"
    exit 1
  fi
else
  # Build the real artifact — this is the part a static grep can't do: it
  # exercises the actual toolchain-generated manifest, not a restated copy of
  # build.gradle's version line that could drift from what the build produces.
  echo "Building the plugin zip for ${tag}..."
  ./gradlew assemble --no-daemon

  zip_path=$(find build/distributions -maxdepth 1 -name 'nf-spawn-*.zip' | sort | tail -1)
  if [ -z "$zip_path" ]; then
    note "no build/distributions/nf-spawn-*.zip found after './gradlew assemble' — nothing to check"
    exit 1
  fi
fi
echo "Built artifact: ${zip_path}"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

if ! unzip -q -o "$zip_path" 'classes/META-INF/MANIFEST.MF' -d "$tmp"; then
  note "could not extract classes/META-INF/MANIFEST.MF from ${zip_path}"
  exit 1
fi

manifest="$tmp/classes/META-INF/MANIFEST.MF"
if [ ! -f "$manifest" ]; then
  note "${zip_path} has no classes/META-INF/MANIFEST.MF"
  exit 1
fi

# MANIFEST.MF wraps long lines with a leading space on the continuation, but
# Plugin-Version is short enough to never wrap in practice; read it as a
# single line to keep this simple and let a genuine format change fail loudly
# below rather than silently mis-parse.
got=$(grep -E '^Plugin-Version:' "$manifest" | sed -E 's/^Plugin-Version:[[:space:]]*//' | tr -d '\r')

if [ -z "$got" ]; then
  note "${zip_path}'s MANIFEST.MF has no Plugin-Version line"
  exit 1
fi

if [ "$got" != "$want" ]; then
  note "the built zip's MANIFEST.MF reports Plugin-Version '$got' but the tag is '$tag' (expected '$want') — build.gradle's version property does not match the tag, or the built artifact is stale"
else
  echo "✅ ${zip_path} reports Plugin-Version ${got} for tag ${tag}"
fi

[ "$fail" -eq 0 ] || exit 1

# Also check the id inside the zip matches, since that's the second half of
# what users copy into nextflow.config as `id 'nf-spawn@X.Y.Z'`.
plugin_id=$(grep -E '^Plugin-Id:' "$manifest" | sed -E 's/^Plugin-Id:[[:space:]]*//' | tr -d '\r')
if [ "$plugin_id" != "nf-spawn" ]; then
  note "${zip_path}'s MANIFEST.MF has Plugin-Id '$plugin_id', want 'nf-spawn'"
fi

[ "$fail" -eq 0 ] || exit 1

# A release must not carry an unreleased-version placeholder in the changelog
# either: the tag is the moment [Unreleased] becomes [X.Y.Z] (see CLAUDE.md),
# and publishing with the section unpromoted means the release notes for
# X.Y.Z say "Unreleased" forever.
if [ -f CHANGELOG.md ] && ! grep -qF "## [${want}]" CHANGELOG.md; then
  note "CHANGELOG.md has no '## [${want}]' section — promote [Unreleased] to [${want}] before tagging"
fi

[ "$fail" -eq 0 ] || exit 1
echo "✅ Release version check passed for ${tag}"
